import { logger } from '../utils/logger';

/**
 * Meta (Facebook/Instagram) Ads API Service
 * Handles campaign creation, management, and performance tracking
 */
class MetaService {
  private accessToken: string;
  private adAccountId: string;
  private apiVersion: string = 'v18.0';
  private baseUrl: string = 'https://graph.facebook.com';

  constructor() {
    this.accessToken = process.env.META_ACCESS_TOKEN || '';
    this.adAccountId = process.env.META_AD_ACCOUNT_ID || '';

    if (!this.accessToken || !this.adAccountId) {
      logger.warn('Meta Ads credentials not configured');
    }
  }

  /**
   * Map an app/legacy objective to the ODAX objective Meta's API requires.
   * Meta now only accepts OUTCOME_* values; older names like CONVERSIONS or
   * WEBSITE_CONVERSIONS are rejected.
   */
  private mapObjective(objective: string): string {
    const key = (objective || '').toUpperCase();
    const map: Record<string, string> = {
      // legacy / app values -> ODAX
      CONVERSIONS: 'OUTCOME_SALES',
      WEBSITE_CONVERSIONS: 'OUTCOME_SALES',
      OFFSITE_CONVERSIONS: 'OUTCOME_SALES',
      APP_INSTALLS: 'OUTCOME_APP_PROMOTION',
      LINK_CLICKS: 'OUTCOME_TRAFFIC',
      TRAFFIC: 'OUTCOME_TRAFFIC',
      REACH: 'OUTCOME_AWARENESS',
      BRAND_AWARENESS: 'OUTCOME_AWARENESS',
      AWARENESS: 'OUTCOME_AWARENESS',
      POST_ENGAGEMENT: 'OUTCOME_ENGAGEMENT',
      ENGAGEMENT: 'OUTCOME_ENGAGEMENT',
      LEAD_GENERATION: 'OUTCOME_LEADS',
      LEADS: 'OUTCOME_LEADS',
      VIDEO_VIEWS: 'OUTCOME_AWARENESS',
      // already ODAX
      OUTCOME_AWARENESS: 'OUTCOME_AWARENESS',
      OUTCOME_TRAFFIC: 'OUTCOME_TRAFFIC',
      OUTCOME_ENGAGEMENT: 'OUTCOME_ENGAGEMENT',
      OUTCOME_LEADS: 'OUTCOME_LEADS',
      OUTCOME_SALES: 'OUTCOME_SALES',
      OUTCOME_APP_PROMOTION: 'OUTCOME_APP_PROMOTION',
    };
    return map[key] || 'OUTCOME_SALES';
  }

  /**
   * Map a human-readable CTA (as generated by the AI, e.g. "Shop Now") to the
   * enum value Meta expects (e.g. SHOP_NOW). Unknown values fall back to
   * SHOP_NOW.
   */
  private mapCta(cta: string): string {
    const key = String(cta || '')
      .trim()
      .toUpperCase()
      .replace(/[\s-]+/g, '_');
    const map: Record<string, string> = {
      SHOP_NOW: 'SHOP_NOW',
      SHOP: 'SHOP_NOW',
      BUY_NOW: 'BUY_NOW',
      BUY: 'BUY_NOW',
      ORDER_NOW: 'ORDER_NOW',
      ORDER_TODAY: 'ORDER_NOW',
      LEARN_MORE: 'LEARN_MORE',
      GET_OFFER: 'GET_OFFER',
      GET_OFFER_VIEW: 'GET_OFFER_VIEW',
      GET_PROMOTIONS: 'GET_PROMOTIONS',
      SIGN_UP: 'SIGN_UP',
      SUBSCRIBE: 'SUBSCRIBE',
      CONTACT_US: 'CONTACT_US',
      GET_A_QUOTE: 'GET_A_QUOTE',
      BOOK_NOW: 'BOOK_NOW',
      ADD_TO_CART: 'ADD_TO_CART',
      SHOP_ON_RETAILER: 'SHOP_ON_RETAILER',
      SEE_DETAILS: 'SEE_DETAILS',
      SEE_MORE: 'SEE_MORE',
      VIEW_PRODUCT: 'VIEW_PRODUCT',
      DOWNLOAD: 'DOWNLOAD',
      MESSAGE_PAGE: 'MESSAGE_PAGE',
      SEND_MESSAGE: 'MESSAGE_PAGE',
      WHATSAPP_MESSAGE: 'WHATSAPP_MESSAGE',
      CALL_NOW: 'CALL_NOW',
      APPLY_NOW: 'APPLY_NOW',
      REGISTER_NOW: 'REGISTER_NOW',
      TRY_NOW: 'TRY_NOW',
      NO_BUTTON: 'NO_BUTTON',
    };
    return map[key] || 'SHOP_NOW';
  }

  /**
   * Build a readable message from a Meta Graph API error object.
   */
  private formatError(err: any): string {
    if (!err) return 'Unknown Meta error';
    const parts = [err.message || 'Meta error'];
    if (err.error_user_title) parts.push(`- ${err.error_user_title}`);
    if (err.error_user_msg) parts.push(`- ${err.error_user_msg}`);
    if (err.error_subcode) parts.push(`(subcode ${err.error_subcode})`);
    return parts.join(' ');
  }

  /**
   * Create a new campaign
   */
  async createCampaign(params: {
    name: string;
    objective: string;
    status: string;
    specialAdCategories?: string[];
  }): Promise<any> {
    try {
      const url = `${this.baseUrl}/${this.apiVersion}/${this.adAccountId}/campaigns`;
      
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          access_token: this.accessToken,
          name: params.name,
          objective: this.mapObjective(params.objective),
          status: params.status,
          special_ad_categories: params.specialAdCategories || [],
          // Required by Meta when not using campaign-level (CBO) budgeting.
          is_adset_budget_sharing_enabled: false,
        }),
      });

      const data: any = await response.json();

      if (data.error) {
        throw new Error(this.formatError(data.error));
      }

      logger.info('Meta campaign created', {
        campaignId: data.id,
        name: params.name,
        objective: this.mapObjective(params.objective),
      });
      return data;
    } catch (error: any) {
      logger.error('Error creating Meta campaign', { error: error.message, params });
      throw new Error(`Failed to create Meta campaign: ${error.message}`);
    }
  }

  /**
   * Create an ad set
   */
  async createAdSet(params: {
    campaignId: string;
    name: string;
    dailyBudget?: number;
    lifetimeBudget?: number;
    billingEvent: string;
    optimizationGoal: string;
    bidAmount?: number;
    bidStrategy?: string;
    promotedObject?: any;
    targeting: any;
    status: string;
  }): Promise<any> {
    try {
      const url = `${this.baseUrl}/${this.apiVersion}/${this.adAccountId}/adsets`;

      // Meta requires the Advantage audience flag to be set explicitly.
      const targeting = {
        ...(params.targeting || {}),
        targeting_automation: {
          advantage_audience: 0,
          ...((params.targeting && params.targeting.targeting_automation) || {}),
        },
      };

      const body: any = {
        access_token: this.accessToken,
        campaign_id: params.campaignId,
        name: params.name,
        billing_event: params.billingEvent,
        optimization_goal: params.optimizationGoal,
        targeting,
        status: params.status,
        // Meta requires an explicit bid strategy when no bid amount is given.
        bid_strategy: params.bidStrategy || 'LOWEST_COST_WITHOUT_CAP',
      };

      if (params.promotedObject) {
        body.promoted_object = params.promotedObject;
      }
      if (params.dailyBudget) {
        body.daily_budget = Math.round(params.dailyBudget * 100); // Convert to cents
      }
      if (params.lifetimeBudget) {
        body.lifetime_budget = Math.round(params.lifetimeBudget * 100);
      }
      if (params.bidAmount) {
        body.bid_amount = Math.round(params.bidAmount * 100);
      }

      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });

      const data: any = await response.json();

      if (data.error) {
        throw new Error(this.formatError(data.error));
      }

      logger.info('Meta ad set created', { adSetId: data.id, name: params.name });
      return data;
    } catch (error: any) {
      logger.error('Error creating Meta ad set', { error: error.message, params });
      throw new Error(`Failed to create Meta ad set: ${error.message}`);
    }
  }

  /**
   * Create an ad creative
   */
  async createAdCreative(params: {
    name: string;
    objectStorySpec: any;
  }): Promise<any> {
    try {
      const url = `${this.baseUrl}/${this.apiVersion}/${this.adAccountId}/adcreatives`;

      // Normalise the CTA to one of Meta's required enum values.
      const spec = params.objectStorySpec ? { ...params.objectStorySpec } : {};
      if (spec.link_data?.call_to_action) {
        spec.link_data = {
          ...spec.link_data,
          call_to_action: {
            ...spec.link_data.call_to_action,
            type: this.mapCta(spec.link_data.call_to_action.type),
          },
        };
      }
      
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          access_token: this.accessToken,
          name: params.name,
          object_story_spec: spec,
        }),
      });

      const data: any = await response.json();

      if (data.error) {
        throw new Error(data.error.message);
      }

      logger.info('Meta ad creative created', { creativeId: data.id });
      return data;
    } catch (error: any) {
      logger.error('Error creating Meta ad creative', { error: error.message });
      throw new Error(`Failed to create Meta ad creative: ${error.message}`);
    }
  }

  /**
   * Create an ad
   */
  async createAd(params: {
    adSetId: string;
    creativeId: string;
    name: string;
    status: string;
  }): Promise<any> {
    try {
      const url = `${this.baseUrl}/${this.apiVersion}/${this.adAccountId}/ads`;
      
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          access_token: this.accessToken,
          adset_id: params.adSetId,
          creative: { creative_id: params.creativeId },
          name: params.name,
          status: params.status,
        }),
      });

      const data: any = await response.json();

      if (data.error) {
        throw new Error(data.error.message);
      }

      logger.info('Meta ad created', { adId: data.id, name: params.name });
      return data;
    } catch (error: any) {
      logger.error('Error creating Meta ad', { error: error.message, params });
      throw new Error(`Failed to create Meta ad: ${error.message}`);
    }
  }

  /**
   * Get campaign insights (performance metrics)
   */
  async getCampaignInsights(campaignId: string, dateRange?: { since: string; until: string }): Promise<any> {
    try {
      let url = `${this.baseUrl}/${this.apiVersion}/${campaignId}/insights`;
      
      const params = new URLSearchParams({
        access_token: this.accessToken,
        fields: 'impressions,clicks,spend,actions,ctr,cpc,cpp',
        level: 'campaign',
      });

      if (dateRange) {
        params.append('time_range', JSON.stringify({
          since: dateRange.since,
          until: dateRange.until,
        }));
      }

      url += `?${params.toString()}`;

      const response = await fetch(url);
      const data: any = await response.json();

      if (data.error) {
        throw new Error(data.error.message);
      }

      return data.data?.[0] || {};
    } catch (error: any) {
      logger.error('Error fetching Meta campaign insights', { error: error.message, campaignId });
      throw new Error(`Failed to fetch insights: ${error.message}`);
    }
  }

  /**
   * Update campaign status (pause/resume)
   */
  async updateCampaignStatus(campaignId: string, status: 'ACTIVE' | 'PAUSED'): Promise<boolean> {
    try {
      const url = `${this.baseUrl}/${this.apiVersion}/${campaignId}`;
      
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          access_token: this.accessToken,
          status: status,
        }),
      });

      const data: any = await response.json();

      if (data.error) {
        throw new Error(this.formatError(data.error));
      }

      logger.info('Meta campaign status updated', { campaignId, status });
      return data.success || true;
    } catch (error: any) {
      logger.error('Error updating Meta campaign status', { error: error.message, campaignId });
      throw new Error(`Failed to update campaign status: ${error.message}`);
    }
  }

  /**
   * Read the current status of a campaign on Meta (for status sync).
   */
  async getCampaignStatus(campaignId: string): Promise<string | null> {
    try {
      const url = `${this.baseUrl}/${this.apiVersion}/${campaignId}?fields=status,effective_status&access_token=${this.accessToken}`;
      const response = await fetch(url);
      const data: any = await response.json();
      if (data.error) throw new Error(this.formatError(data.error));
      return data.status || null;
    } catch (error: any) {
      logger.warn('Error reading Meta campaign status', { error: error.message, campaignId });
      return null;
    }
  }

  /**
   * Update a campaign's daily budget (Meta expects minor units / cents).
   */
  async updateCampaignBudget(campaignId: string, dailyBudget: number): Promise<boolean> {
    const url = `${this.baseUrl}/${this.apiVersion}/${campaignId}`;
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        access_token: this.accessToken,
        daily_budget: Math.round(dailyBudget * 100),
      }),
    });
    const data: any = await response.json();
    if (data.error) throw new Error(this.formatError(data.error));
    logger.info('Meta campaign budget updated', { campaignId, dailyBudget });
    return data.success || true;
  }

  /**
   * Update an ad set's daily budget.
   */
  async updateAdSetBudget(adSetId: string, dailyBudget: number): Promise<boolean> {
    const url = `${this.baseUrl}/${this.apiVersion}/${adSetId}`;
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        access_token: this.accessToken,
        daily_budget: Math.round(dailyBudget * 100),
      }),
    });
    const data: any = await response.json();
    if (data.error) throw new Error(this.formatError(data.error));
    logger.info('Meta ad set budget updated', { adSetId, dailyBudget });
    return data.success || true;
  }

  /**
   * Get day-by-day insights for a campaign/adset/ad.
   * `level`: 'campaign' | 'adset' | 'ad'
   */
  async getInsightsByDay(
    objectId: string,
    level: 'campaign' | 'adset' | 'ad',
    datePreset: string = 'last_30d'
  ): Promise<any[]> {
    try {
      const params = new URLSearchParams({
        access_token: this.accessToken,
        fields: 'impressions,clicks,spend,actions,ctr,cpc',
        level,
        date_preset: datePreset,
        time_increment: '1', // one row per day
      });
      const url = `${this.baseUrl}/${this.apiVersion}/${objectId}/insights?${params.toString()}`;
      const response = await fetch(url);
      const data: any = await response.json();
      if (data.error) throw new Error(this.formatError(data.error));
      return data.data || [];
    } catch (error: any) {
      logger.warn('Error fetching daily insights', { error: error.message, objectId, level });
      return [];
    }
  }

  /**
   * List child objects (adsets of a campaign, or ads of an adset) with status.
   */
  async listChildren(parentId: string, edge: 'adsets' | 'ads'): Promise<any[]> {
    try {
      const url = `${this.baseUrl}/${this.apiVersion}/${parentId}/${edge}?fields=id,name,status,daily_budget&limit=200&access_token=${this.accessToken}`;
      const response = await fetch(url);
      const data: any = await response.json();
      if (data.error) throw new Error(this.formatError(data.error));
      return data.data || [];
    } catch (error: any) {
      logger.warn('Error listing children', { error: error.message, parentId, edge });
      return [];
    }
  }

  /**
   * Test connection to Meta API
   */
  async testConnection(): Promise<boolean> {
    try {
      const url = `${this.baseUrl}/${this.apiVersion}/me?access_token=${this.accessToken}`;
      const response = await fetch(url);
      const data: any = await response.json();
      return !data.error;
    } catch (error) {
      logger.error('Meta connection test failed', { error });
      return false;
    }
  }
}

export const metaService = new MetaService();
export default metaService;

